### ISSUE TITLE
Use Heap as the priority queue data structure

### ISSUE THREAD

**Issue by Ascenio** [Renesanse/worker_manager#10]
I see currently the priority queue is implemented in a List but working as a Queue, such that the it picks elements from the front and the position of a Task corresponds to its priority. I suggest changing to a Heap because it handles the priorities _by itself_, you just adds something to it and by the time you ask it to get a Task it gives you the one who "deservers" most (sorry, it was the only term I could think of). Currently there is the `high`, `regular` and `low` priorities, but there is no middle term like ultra-low or regular-low-ish. Heap handles it such that you pass priority by value (1, 2, 3...) and so allows more customization.

**Comment by Ascenio** [comment]
Luckly there's already a implementation. Take a look at [HeapPriorityQueue](https://api.flutter.dev/flutter/package-collection_collection/HeapPriorityQueue-class.html)

**Comment by Renesanse** [comment]
Hi @Ascenio, thx for creating this issue. Your idea seems legit. I implemented it in this branch https://github.com/Renesanse/worker_manager/tree/HeapPriorityQueue_test
May I ask you to review my code and tell is it enough priority levels?
