### ISSUE TITLE
[macos]nvalid argument(s): Illegal argument in isolate message : (object is a closure

### ISSUE THREAD

**Issue by chongbo2013** [Renesanse/worker_manager#18]
[macos]nvalid argument(s): Illegal argument in isolate message : (object is a closure
macos pls

**Comment by Sameerkash** [comment]
@chongbo2013, The function you're calling cannot be an instance of a class, it has to be a top-level function; 
Refer [this](https://stackoverflow.com/questions/51998995/invalid-arguments-illegal-argument-in-isolate-message-object-is-a-closure) post for more details.

make your function static or top level.

**Comment by Renesanse** [comment]
Hello @chongbo2013, @Sameerkash answered to your question, thx.
