### ISSUE TITLE
Isolate main is already scheduled on mutator thread 0xa8f9f400, failed to schedule from os 

### ISSUE THREAD

**Issue by winterdl** [Renesanse/worker_manager#19]
I have a listview, I use Executor to run a task to get data in background for continuous scroll listview, the code run ok, but it's random crash on real device, release build with error message from the log:

`../../third_party/dart/runtime/vm/dart_api_impl.cc: 1708: error: Isolate main is already scheduled on mutator thread 0xa8f9f400, failed to schedule from os thread 0x5b27`

if I remove worker_manager, the app run well without crash, I dont know why the crash occured by chance, not by request data because the app run well without create isolate.

```
 Flutter (Channel master, 1.25.0-5.0.pre.106, on Mac OS X 10.14.6
    • Flutter version 1.25.0-5.0.pre.106 at /Users/admin/dev/flutter/flutter
    • Framework revision bd68225598 (10 hours ago), 2020-12-07 19:58:04 -0500
    • Engine revision a26e80c931
    • Dart version 2.12.0 (build 2.12.0-125.0.dev)
```

addition logs:

```
pthread_create failed: couldn't allocate 528384-bytes mapped space: Out of memory
W/libc    ( 9741): pthread_create failed: couldn't allocate 528384-bytes mapped space: Out of memory
```

**Comment by Renesanse** [comment]
Hello, @winterdl did you tried compute method instead? Can you clarify your device model? The issue looks weird and looks like it came from dart VM, not a library around isolates. After your clarifying, I will send logs and all information to dart VM team, thx!

**Comment by winterdl** [comment]
Sorry for late reply, for the release of my app, I have to removed code related to isolate, the exception occured when creating isolate manual, not using your lib. Thank you for your help.
