### ISSUE TITLE
Null-safety migration

### ISSUE THREAD

**Issue by RTrackerDev** [Renesanse/worker_manager#21]
Do you plan to migrate to null-safety?

**Comment by Renesanse** [comment]
Yes, sure

**Comment by galunecandrey** [comment]
Do you have any updates?

**Comment by Renesanse** [comment]
Hello @galunecandrey, still waiting shader warm up.

**Comment by noinskit** [comment]
@Renesanse could you please explain how this shaded warm up problem is blocking null-safety migration?
Is there any bug tracking it?

**Comment by Renesanse** [comment]
Please try this branch, I really need your feedback guys, thx! https://github.com/Renesanse/worker_manager/tree/null_safety
