### ISSUE TITLE
error in example

### ISSUE THREAD

**Issue by aidooyaw1992** [Renesanse/worker_manager#3]
whenever i run the code, i get this

I/flutter (17353): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter (17353): The following RangeError was thrown while handling a gesture:
I/flutter (17353): RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (17353):
I/flutter (17353): When the exception was thrown, this was the stack:
I/flutter (17353): #0      List.[] (dart:core-patch/growable_array.dart:147:60)
I/flutter (17353): #1      _RegularScheduler._warmUpFirst (package:worker_manager/scheduler.dart:42:42)
I/flutter (17353): #2      _RegularScheduler.manageQueue (package:worker_manager/scheduler.dart:24:7)
I/flutter (17353): #3      _WorkerManager.addTask (package:worker_manager/executor.dart:54:50)
I/flutter (17353): #4      _PendingUploadsPageState.build.<anonymous closure> (package:ereader/pages/pending_uploads.dart:98:34)
I/flutter (17353): #5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:654:14)
I/flutter (17353): #6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:729:32)
I/flutter (17353): #7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter (17353): #8      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:365:11)
I/flutter (17353): #9      TapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:275:7)
I/flutter (17353): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:455:9)
I/flutter (17353): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:75:13)
I/flutter (17353): #12     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:102:11)
I/flutter (17353): #13     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
I/flutter (17353): #14     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter (17353): #15     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter (17353): #16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter (17353): #17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter (17353): #21     _invoke1 (dart:ui/hooks.dart:263:10)
I/flutter (17353): #22     _dispatchPointerDataPacket (dart:ui/hooks.dart:172:5)
I/flutter (17353): (elided 3 frames from package dart:async)
I/flutter (17353):
I/flutter (17353): Handler: "onTap"
I/flutter (17353): Recognizer:
I/flutter (17353):   TapGestureRecognizer#5b7f1
I/flutter (17353): ═════════

**Comment by Renesanse** [comment]
@aidooyaw1992 Hello! Did you initialized Executor with 0 isolatePoolSize ?

**Comment by aidooyaw1992** [comment]
yh i did all that
