### ISSUE TITLE
What does the warm up method do?

### ISSUE THREAD

**Issue by basketball-ico** [Renesanse/worker_manager#33]
What does the warm up method do? and how i know how many isolatesCount value should i pass?

**Comment by Renesanse** [comment]
Hi, executor preparing scheduler (spawning isolates, opening ports, and waits all isolates to receive open confirmation) Out of the box executor spawn isolates based on the number of your machine cores - 1. But you can use 2 or 3 isolates - it's optimal configuration for all mobile devices.
