### ISSUE TITLE
How can I know if the warmUp method was called or call warmUpr safely more than 1 time?

### ISSUE THREAD

**Issue by basketball-ico** [Renesanse/worker_manager#37]
Hi, i want to use this in my package but I don't want the user call warmUp in the main.

I want to call it only in the class that use it, and i want to do something like this?
```dart
If(Executor.canWarmUp){
  Executor().warmUp();
}
```
But ideally I want to call `Executor().warmUp();` as many times i want and the executor do this check internally, to no add more Isolate wrappers to the pool

**Comment by Renesanse** [comment]
Hm, it could be useful, do you think to dispose implementation would be useful too in your case?

**Comment by Renesanse** [comment]
resolved in https://github.com/Renesanse/worker_manager/commit/29cc776e214b23a76407d9aa7edde251a282990a
