### ISSUE TITLE
why throw a Type when timeout

### ISSUE THREAD

**Issue by windrunner414** [Renesanse/worker_manager#4]
I think `throw TimeoutException("worker execute timeout", task.timeout)` is better than throw a type `TimeoutException`

**Comment by Renesanse** [comment]
Thx for point to it =), Closed.

**Comment by windrunner414** [comment]
@Renesanse hi, TimeoutException has a field 'duration', I think it should be set.
just use `TimeoutException('message', task.timeout);`

**Comment by Renesanse** [comment]
Yes, you are right. I didn't have a time to test  possibility to send full Timeout exception, because some times if you have an exception with big  call stack, you are not able to send it throw ports. I suppose it is about serialization size limitation.
This code is workaround for this case:
```dart
      try {
        sendPort.send(result);
      } catch (_) {
        sendPort.send(Result.error('isolate error: ${(result as ErrorResult).error.toString()}'));
      }
```
