### ISSUE TITLE
Kill isolate pool

### ISSUE THREAD

**Issue by TimWhiting** [Renesanse/worker_manager#40]
There doesn't seem to be a way to dispose of the Executor. Use case is I have a command line app, and the process just hangs when all of the processing is done since the isolates are still alive. I would like the app to exit at that point, so I need a way of killing the isolates. I see there is a kill method on isolate, but the executor pool is private.

**Comment by Renesanse** [comment]
Hi Tim! Good point, thx for your request.

**Comment by Renesanse** [comment]
resolved in https://github.com/Renesanse/worker_manager/commit/29cc776e214b23a76407d9aa7edde251a282990a
