### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by kevinxxq** [Renesanse/worker_manager#42]
Hi there,
When I use this package,  it shows twice isolates than cores of my CPU. Normally the quantity is 8 and current it is 16. The memory usage is much higher than normal level(~3.5G comparing with ~350M)

![image](https://user-images.githubusercontent.com/55800697/131765065-a550d6eb-54c1-4c47-a95a-1111a03b7afc.png)
![image](https://user-images.githubusercontent.com/55800697/131765098-b210e598-c3fe-47c4-b99c-5a807ba54b56.png)

My question is that when I call it as below
final result1 = await Executor().execute(arg1: someRepo, arg2: page, fun2: fetchUsers);
final result2 = await Executor().execute(arg1: someRepo, arg2: page, fun2: fetchUsers);

Asume that the fetchUsers will take very long time, so the Executor() knows that arrange the tasks to different isolates or queue. Right? the opposite is crash.

Thank you.

**Comment by Renesanse** [comment]
Well, I suggest you to use fake implementation for execute method while developing the application. Explanation of this problem is: each time you call hot restart, executor spawn isolates(cause the main method runs anyway) and don't killing already spawned. I will update readme and try to kill old isolates somehow, thx for reporting the issue!

**Comment by Renesanse** [comment]
I found google devs have been close the issue: https://github.com/flutter/flutter/issues/20764. Maybe you have virtual threads? Can you pass the log parameter as true in warmUp method and tell me how many isolates have been spawned. Btw, you can configure num of isolates in the wurmUp method by passing isolateCount parameter.

**Comment by kevinxxq** [comment]
Thank you for quick feedback and for the helpful tips.
Yes, it happens during hot restart.

_Maybe you have virtual threads? Can you pass the log parameter as true in warmUp method and tell me how many isolates have been spawned._ 
CPU	Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz with 8 logical cores. 
the log: flutter: 7 has been spawned. 

Such issues took place during the dart plugin update(need restart the IDE-vs code) and there may be something stuck for hot restart, it was just a blank panel without content during hot restart.

After I restart the IDE, the errors showed that it is from the exceptions of isolate(object is a FunctionType dart isolate) but the exceptions are not thrown out before I restart IDE. 

_Btw, you can configure num of isolates in the wurmUp method by passing isolateCount parameter._
If I set isolateCount, it will have fixed quantity on different kinds of computers. Right? Is it better to get it through your implementation (int get numberOfProcessors => Platform.numberOfProcessors) ?

Thank you.

**Comment by Renesanse** [comment]
isolateCount will not fix the bug you figured out, it is just a useful thing if you want to decrease start time on low-performance devices.

**Comment by kevinxxq** [comment]
Thank you. Just wait for the official update for Isolates to accept more types of arguments.
