### ISSUE TITLE
Does your packages supports "multitreading" for web?

### ISSUE THREAD

**Issue by bambinoua** [Renesanse/worker_manager#49]
Does your packages supports "multitreading" for web?

**Comment by bambinoua** [comment]
Does your packages supports "multitreading" for web?

**Comment by Renesanse** [comment]
Hi, @bambinoua please look carefully on readme file

**Comment by bambinoua** [comment]
So why your package has a mark **Web** (compatible with flutter on web platform) if package actually does not implement `Worker` as is? It's a little confusing when you read _yes, web is supported_ but really _oops, under construction_.

> Executor is a library for running CPU intensive functions inside a separate dart isolate.

But this is not true for web.
