### ISSUE TITLE
End works immediately

### ISSUE THREAD

**Issue by Akash-Manjhi** [Renesanse/worker_manager#50]
When I try to execute some task in executor, it starts the work and then ends the works immediately. I am hitting some API in the function and the task does not complete.
This is the log.
added task with number -9007199254740992
isolate with task number -9007199254740992 begins work
calllll---->
request type----->lms_content_video
isolate with task number -9007199254740992 ends work

```
Cancelable<void> lastKnownOperation = await Executor().execute(arg1: UploadRequest(
        fileName: fileName,
        bytes: fileData.file.bytes,
        user: userStream.value,
        type: type == AppConstants.LMS_CONTENT_FILE_DOC_TYPE
            ? 'lms_content_downloadable'
            : type == AppConstants.LMS_CONTENT_FILE_VIDEO_TYPE
            ? 'lms_content_video'
            : 'lms_content_audio'), fun1: uploadVideoFile).next(

    );

    lastKnownOperation.cancel();
```
Can anyone help me out.
Thanks!🙂

**Comment by Renesanse** [comment]
please add onError callback and update your issue with logs

**Comment by Renesanse** [comment]
Did you test uploading video by compute method, probably this case is not suitable for isolates, can you test `compute` from foundation lib?

**Comment by Akash-Manjhi** [comment]
OKay will try and check.
