### ISSUE TITLE
Cancelable.mergeAll get error Bad State after cancel

### ISSUE THREAD

**Issue by dafinoer** [Renesanse/worker_manager#53]
hi, i try to uploading image with multiple `Executor` with `Cancelable.mergeAll()`, on process uploading, i try to cancel upload, but i get error log like this: 

```
Bad state: Stream has already been listened to.
------- STACK TRACE -------
#0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
#1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
#2      _StreamImpl.listen (dart:async/stream_impl.dart:473:9)
#3      _ReceivePortImpl.listen (dart:isolate-patch/isolate_patch.dart:91:31)
#4      WorkerImpl.initialize (package:worker_manager/src/worker/worker_io.dart:24:29)
<asynchronous suspension>
```

it's a bug?, but before, i try upload single file and using `Executor().execute()` and try to kill isolate when the process upload, everything good.

**Comment by Renesanse** [comment]
resolved in https://github.com/Renesanse/worker_manager/commit/d13115284ee1c60c63e9c3c06851ea59f4660cd5
