### ISSUE TITLE
Close isolate pool

### ISSUE THREAD

**Issue by Andrflor** [Renesanse/worker_manager#56]
Almost the same as the #40 issue

Imagine a dart cli program with:
```dart
main() async {
  await Executor().warmUp();
  final lines = await loadFile();
  for (final line in lines) {
    Executor().execute(arg1: line, fun1: callback).then(print);
  }
}
```
If i don't call dispose the program will never end.
If i call dispose the program will end before any print.

There doesn't seem to be a way to close the isolate pool.
(Wait for the queue to be empty before killing the pool)

**Comment by Renesanse** [comment]
well, probably something like getter to figure out that queue is empty and nothing runs in isolates fits to solve your problem?

**Comment by Renesanse** [comment]
> The idea was to be able to use the executor without having to save all the futures in a list and then waiting them all.

can you provide another example of your taking about above

**Comment by Andrflor** [comment]
I must write

```dart 
main() async {
  await Executor().warmUp();
  final lines = await loadFile();
  await Future.wait(lines.map(
      (line) => Executor().execute(arg1: line, fun1: callback).then(print)));
  Executor().dispose();
}
```

**Comment by Renesanse** [comment]
well, as I understand you correctly u don't want to wait
