### ISSUE TITLE
Types declaration with api 2.3.0 when implicit_cast is disabled

### ISSUE THREAD

**Issue by autolainen** [Renesanse/worker_manager#6]
Hello!
We tried to move to 2.3.0 and realised that we need to declare dummy type parameters on Runnable and on Task:

```
  Task<String, String, String, String, String, Uint8List> task;

  @override
  void initState() {
    super.initState();
    SchedulerBinding.instance.addPostFrameCallback((_) async {
      File downloadedFile;
      task = Task<String, String, String, String, String, Uint8List>(
          runnable: Runnable<String, String, String, String, String, Uint8List>(
              arg1: widget.url, fun1: downloadFile));
      Executor().addTask<Uint8List>(task: task).listen((bytes) async {
```
That's because we have implicit_cast disabled in our project. The previous api works fine and has no such drawback so we'll stick with it.

Thanks for your efforts anyway!

**Comment by Renesanse** [comment]
Well, I figured out people found uncomfortable to create a bundle for static methods with one parameter. If you don't want to cancel the Task, you probably shouldn't declare task variable inside a class body. But, if you want to, you can write this:
```dart
Task<String, void, void, void, void, Uint8List> task;
```
I agree -  looks bad. But, it looks ok if you have 3 args 
```dart
Task<SomeRepository, String, int, void, void, Response> task;
```
This is me trying to work with dart limitation of run something in the separate isolate. Probably, I should create something like Task1, Task2, Task3 ... If you have any ideas to solve this problem, I am waiting for your PR =)

**Comment by Renesanse** [comment]
Well, I figured out people found uncomfortable to create a bundle for static methods with one parameter. If you don't want to cancel the Task, you probably shouldn't declare task variable inside a class body. But, if you want to, you can write this:

Task<String, void, void, void, void, Uint8List> task;
I agree - looks bad. But, it looks ok if you have 3 args

Task<SomeRepository, String, int, void, void, Response> task;
This is me trying to work with dart limitation of run something in the separate isolate. Probably, I should create something like Task1, Task2, Task3 ... If you have any ideas to solve this problem, I am waiting for your PR =)

**Comment by Renesanse** [comment]
> Hello!
> We tried to move to 2.3.0 and realised that we need to declare dummy type parameters on Runnable and on Task:
> 
> ```
>   Task<String, String, String, String, String, Uint8List> task;
> 
>   @override
>   void initState() {
>     super.initState();
>     SchedulerBinding.instance.addPostFrameCallback((_) async {
>       File downloadedFile;
>       task = Task<String, String, String, String, String, Uint8List>(
>           runnable: Runnable<String, String, String, String, String, Uint8List>(
>               arg1: widget.url, fun1: downloadFile));
>       Executor().addTask<Uint8List>(task: task).listen((bytes) async {
> ```
> 
> That's because we have implicit_cast disabled in our project. The previous api works fine and has no such drawback so we'll stick with it.
> 
> Thanks for your efforts anyway!

Added Task1, Task2, Task3 and removed 5th parameter, close for now =)
