### ISSUE TITLE
can not support  platform MethodChannel function  ?

### ISSUE THREAD

**Issue by sihaixuan** [Renesanse/worker_manager#70]
for example:
static Future<void> test() async {
    await _channel.invokeMethod('test');
  }

static void  test2(int arg){
    test();

}

 Executor().execute(arg1: 0, fun1: test2);

report error,log is here:

Binding has not yet been initialized.
The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.

**Comment by Renesanse** [comment]
hi, I guess this lib can be a solution for your problem, I need time to research theirs way to communicate with method channels via isolates. https://pub.dev/packages/flutter_isolate
