### ISSUE TITLE
exception throws when using with GetXController

### ISSUE THREAD

**Issue by mgu1206** [Renesanse/worker_manager#75]
Hi I am trying to use worker_manager with GetXController to manage state.

I am trying to huge copy job via worker_manager with multiple isolates.

But when I add Obx data in widget, it throw exception.

here is code snippet

- MyWwork.dart
  ...
Executor().execute(arg1: 1, fun1: HugeWork).then((value) {
      controller.setStep(STEP_ENUM.SOME_STEP);
      NextWork();
    });
...

- main.dart
Widget build(BuildContext context) {
    var controller = Get.put(BackupModel());
...
children: <Widget>[
            Obx(() => Text('current step : ${controller.getStep()}')),...]
...

the exception occurred in worker_io.dart line 65

Exception has occurred.
ArgumentError (Invalid argument(s): Illegal argument in isolate message: (object extends NativeWrapper - Library:'dart:ui' Class: Paragraph))

I using worker_manager version 4.5.0

Am I using this library not properly?

**Comment by Renesanse** [comment]
pls show me HugeWork function

**Comment by mgu1206** [comment]
@Renesanse sorry it was my mistake. I missunderstand about isolate.
