### ISSUE TITLE
Communication between Tasks

### ISSUE THREAD

**Issue by wajahat414** [Renesanse/worker_manager#76]
I was wondering is there any method available for  message passing between tasks, can you add an example to tell how we can use this library to  communicates between different isolates

**Comment by Renesanse** [comment]
very interesting use case, after some investigations I will back with answer

**Comment by Renesanse** [comment]
After investigation I founded that it is impossible to send ReseivePort from another isolate to suite up this to listen inside a function or callback you provided in execute method. That means you can listen messages inside another isolate, but u can't send this receive port to listen for messages somewhere else  or listen by provided callback.

**Comment by wajahat414** [comment]
no thats possible, we send the recieve port from the main thread to isolate, isolate can send data to that recieved port, send data means it can also send its own recieve port to main thread ,so two way communication happens

**Comment by Renesanse** [comment]
> no thats possible, we send the recieve port from the main thread to isolate, isolate can send data to that recieved port, send data means it can also send its own recieve port to main thread ,so two way communication happens
Are you sure that you can send Receive port instead of SendPort from ReceivePort?

**Comment by wajahat414** [comment]
Recieved Port has a Parameter of Type Send Port , The Below Code is an example to what I meant;
'
import 'deserialize_isolate.dart';

void main() async {

    ReceivePort receivePort = ReceivePort();
    // Serialized object
    var serializedObject = '{"name":"John", "age":30}';
    // Spawn a new isolate
    await Isolate.spawn(deserialize, receivePort.sendPort, serializedObject);
    // Listen for the deserialized object
    receivePort.listen((deserializedObject) {
        // Handle the deserialized object
        print(deserializedObject);
    });
}

//SerializeedFunction

void deserialize(SendPort sendPort, dynamic serializedObject) async {
    // Deserialize the object
    var object = jsonDecode(serializedObject);
    // Send the deserialized object back to the main isolate
    sendPort.send(object);
}

**Comment by wajahat414** [comment]
Also refer Package isolate_handler , which is used for inter isolate  communication,

**Comment by Renesanse** [comment]
@wajahat414 hi again, pls try version 5.0.0 and share some feedback. If you will find bugs or any unexpected behaviour, pls reopen this issue.
