### ISSUE TITLE
Read SharedPreferences value

### ISSUE THREAD

**Issue by Dev11-ultroNeous** [Renesanse/worker_manager#79]
Hi
I try to get string data from shared preferences using fun1 method but show this type of error

Unhandled Exception: Binding has not yet been initialized.
The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.
#0      BindingBase.checkInstance.<anonymous closure> (package:flutter<…>

**Comment by Renesanse** [comment]
Hi, I see your problem, unfortunately dart doesn’t support external libs inside another isolates, that means you should get your value from prefs in main isolate, but if it is a json, you better to process it by worker manager. Dart team promising that they will add external libs support for different isolates, pls follow the updates.

**Comment by Renesanse** [comment]
Also you can try another lib which allow you to do that, but it is really hacky way to achieve the goal. I wouldn’t recommend to do this.
