### ISSUE TITLE
Version solving failed

### ISSUE THREAD

**Issue by vavadiyahiren** [Renesanse/worker_manager#8]
I have started a new project and just added the dependency but it got failed at verification can you check where it went wrong 
```

Because every version of flutter_test from sdk depends on async 2.4.0 and worker_manager >=2.4.8 depends on async ^2.4.1, flutter_test from sdk is incompatible with worker_manager >=2.4.8.

So, because taskdemo depends on both worker_manager ^2.5.0 and flutter_test any from sdk, version solving failed.
pub get failed (1; So, because taskdemo depends on both worker_manager ^2.5.0 and flutter_test any from sdk, version solving failed.)
```

**Comment by Renesanse** [comment]
Hello! Please, upgrade your async dependency version from 2.4.0 to 2.4.1. worker_manager works with latests dependencies available in pub

**Comment by Renesanse** [comment]
Also you can use just a test dependency instead of flutter_test. Because flutter_test works with old async package
