### ISSUE TITLE
Can I replace Isolate in worker_io.dart with flutter_Isolate package?

### ISSUE THREAD

**Issue by Dev11-ultroNeous** [Renesanse/worker_manager#81]
Hi
I have to try to replace the Isolate with the flutter_isolate package on the worker_io.dart file for my custom functionality. but  I am facing some issues, 
kindly suggest  solution 

Issues:
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message : (object is a regular Dart Instance)
#0      _SendPortImpl._sendInternal (dart:isolate-patch/isolate_patch.dart:249:43)
#1      _SendPortImpl.send (dart:isolate-patch/isolate_patch.dart:230:5)
#2      WorkerImpl.work (package:demo/worker_manager/src/worker/worker_io.dart:66:15)
#3      _Executor._schedule (package:demo/worker_manager/src/scheduling/executor.dart:166:26)
#4      _Executor.execute.executing (package:demo/worker_manager/src/scheduling/executor.dart:120:9)
#5      _Executor.execute (package:demo/worker_manager/src/scheduling/executor.dart:148:12)
#6      ProgressCubit.getlocal (package:demo/bloc/progresscubit/progress_cubit.dart:38:16)
#7      HomePage.build.<anonymous closure> (package:demo/home.dart:53:27)

**Comment by Renesanse** [comment]
do you have public repo to test?

**Comment by Dev11-ultroNeous** [comment]
> do you have public repo to test?

Hi @Renesanse 
Yes, I have one repo here it is
https://github.com/Dev11-ultroNeous/workers

Kindly check it
Thank you

**Comment by Dev11-ultroNeous** [comment]
@Renesanse 
Did you get a chance to have a look?

**Comment by asiteandroid** [comment]
@Renesanse ,

Curious to know about the updates.  Did you tried with flutter_isolates?

**Comment by Renesanse** [comment]
Sorry, I was busy last time. I hope I will able to understand about is it possible to use flutter_isolate in worker_manager at the end of this week

**Comment by Renesanse** [comment]
I have no idea how to resolve your problem for now, sorry.
