### ISSUE TITLE
object is unsendable

### ISSUE THREAD

**Issue by Reprevise** [Renesanse/worker_manager#86]
Ever since upgrading to worker_manager 6.0, everything that I try and send is now "unsendable" through the SendPort.

**Comment by Renesanse** [comment]
@Reprevise hi, pls provide an example to reproduce the bug

**Comment by Reprevise** [comment]
Apologies, I was sending something over an isolate that is not able to be sent (in this case I was passing a Dio `Response` object into the function being passed to the isolate which contains a `CancelToken` which has a `Completer` that cannot be sent over isolates). The fix was to create a variable containing only the response `data` and then passing that along to the isolate instead of the whole `Response` object.
